# -*- coding: utf-8 -*-
"""Faisal_Python_project_BADA_FEB2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16X9Mpsh-ivUqbwPXa3Lhlao0xUBizOjl

Q&A 1 : IMPORT 2 CSV FILE AND NAME THEM
"""

import pandas as pd
import numpy as np



df_employee = pd.read_csv('/content/sample_data/Employee_Details.csv')
df_employee

import pandas as pd
import numpy as np

df_health = pd.read_csv('/content/sample_data/Employee_Health.csv')
df_employee

"""Q&A 2 : CLEAN RAW DATA FOR EACH DATAFRAME

"""

df_employee = df_employee.drop_duplicates()
df_employee

df_health = df_health.drop_duplicates()
df_health

"""Q&A 2b"""

df_health['Name'] = df_health['Name'].str.strip('/123_.')
df_health

"""Q&A 2c Make numeric value o and 1 for smoking coloum"""

df_health['SmokingStatus'] = df_health['SmokingStatus'].replace({'Smoker' : 1 , 'Non-Smoker' : 0})
df_health

df_employee['Name'] = df_employee['Name'].str.strip('/123_.')
df_employee

# Q&A 2d Split date and time

df_employee['LastLogin'] = pd.to_datetime(df_employee['LastLogin'])
df_employee['Last_Login_Date'] = df_employee['LastLogin'].dt.date
df_employee['Last_Login_Time'] = df_employee['LastLogin'].dt.time
df_employee[['LastLogin', 'Last_Login_Date', 'Last_Login_Time']].head()

"""Q&A 2e Make all department-names same case (upper of lower)"""

df_employee['Department'] = df_employee['Department'].str.upper()
df_employee

df_employee['Department'] = df_employee['Department'].str.lower()
df_employee

"""Q&A 2f Replace all null department-names with Unknown Department"""

df_employee['Department'] = df_employee['Department'].fillna('Unknown department')
df_employee

"""Q&A 3a Mean age and stresslevel of employees"""

import numpy as np

average_age = np.mean(df_employee['Age'])
print(average_age)

"""Q&A 3b Median of workhours"""

import numpy as np
import pandas as pd


df_health = pd.read_csv('/content/sample_data/Employee_Health.csv')

median_workhours = np.nanmedian(df_health['WorkHours'])
print(median_workhours)

"""Q&A 3c"""

import numpy as np
import pandas as pd

df_health_sleephours = df_health['SleepHours'] # Extract the 'SleepHours' column as a Series
min_sleephour = np.nanmin(df_health_sleephours)
print(min_sleephour)

"""Q&A 3d"""

import numpy as np
import pandas as pd

df_health_StepCount = df_health['StepCount'] # Extract the 'SleepHours' column as a Series
max_StepCount = np.nanmax(df_health_StepCount)
print(max_StepCount)

"""Q&A 4a Merge Dataframes outer and inner"""

df_merge_outer = pd.merge(df_employee, df_health, on='Name', how='outer')
df_merge_outer

# inner merge

import pandas as pd

df_merge_inner = pd.merge(df_employee, df_health, on='EmployeeID', how='inner')
df_merge_inner

"""Q&A 4b Group gender by department"""

import pandas as pd
df_merge_inner = df_merge_inner.groupby('Department_x')['Gender_y'].value_counts()
df_merge_inner

"""Q&A 4c Average Productivity by Department"""

import pandas as pd
df_merge_outer = df_merge_outer.groupby('Department_y')['ProductivityScore'].mean()
df_merge_outer

"""Q&A 4D Order by Productivity score"""

df_health_productivity = df_health.sort_values(by='ProductivityScore', ascending=False)
df_health_productivity

"""**4.e Correlation **"""

import pandas as pd

df_health_correlation = df_health[['WorkHours','SleepHours','ProductivityScore']].corr()
df_health_correlation

"""Visualization"""

# Gemini used

from matplotlib import colors
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

plt.figure(figsize = (12, 8))
df_employee = pd.read_csv('/content/sample_data/Employee_Details.csv')
df_employee

# Calculate the number of employees per department
department_counts = df_employee['Department'].value_counts() #.reset_index()
department_counts.columns = ['Department', 'Total Employees']
department_counts



# Define colors for the bars (ensure enough colors for all departments)
# You can extend this list or use a colormap if there are many departments
#plot_colors = ['red','green','blue','cyan','purple','orange', 'brown', 'pink', 'gray', 'olive']

# Create a horizontal bar chart
#sns.barplot(x='Total Employees', y='Department', data=department_counts, palette=plot_colors[:len(department_counts)], hue='Department', legend=False)

#plt.xlabel('Total Employees')
#plt.ylabel('Department')
#plt.title('Number of Employees by Department')
#plt.tight_layout() # Adjust layout to prevent labels from overlapping
#plt.show()

from matplotlib import colors
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

#plt.figure(figsize = (10,8))


#plot_colors = ['red','green','blue','cyan','purple','orange']

df_employee = df_employee.groupby('Department')['Gender'].count()
df_employee